# Generated by Django 4.0.2 on 2022-02-23 09:44

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=model_utils.fields.StatusField(choices=[('enable', 'enable'), ('disabled', 'disabled')], default='enable', max_length=100, no_check_for_status=True),
        ),
    ]
